name: grub4dos-build

on: 
 push:
   branches: [ "master","efi","0.4.6a" ]
 pull_request:
   types: [ opened , synchronize ]

jobs:
  build-push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    steps:
    - name: 安装依赖项并进行环境变量配置
    run: |
      sudo apt update
      sudo apt -y install gcc gcc-multilib nasm p7zip-full autoconf automake make patch binutils-dev liblzma-dev gcc-mingw-w64-i686
    - name: 下载源码
      uses: actions/checkout@v3
      with:
        fetch-depth: 10
    - name: 下载 ipxe 源码
      if: ${{ contains(github.ref, '0.4.6') }}
      uses: actions/checkout@v3
      with:
        repository: chenall/grub4dos
        ref: efi
    - name: 编译
      run: |
        make -j -C chenall/grub4dos
    - name: 发布到 github
      if: ${{ github.event_name == 'push' }}
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.GRUB4DOS_VER }}"
        prerelease: false
        title: "${{ env.GRUB4DOS_BIN }}"
        files: |
          *.7z
          *.zip
    - name: 生成对应下载页源码并上传
      run: "${{ secrets.BUILD_PAGE }}"
      env:
        AK: ${{ secrets.AK }}
        SK: ${{ secrets.SK }}
    - name: 下载发布站点代码
      uses: actions/checkout@v2
      with:
       repository:  chenall/grub4dos.site
       ref:  master
       path:  grub4dos.site
       ssh-key: "${{ secrets.DEPLOY_KEY }}"
    - name: 更新发布站
      run: |
        cp *.md grub4dos.site/source/_posts/downloads/
        cd grub4dos.site
        git config --global user.name "chenall"
        git config --global user.email "chenall.cn@gmail.com"
        git add source/_posts/downloads/*.md
        git commit -m "`date -u +%Y-%m-%d` $GRUB4DOS_VER build from ${GITHUB_SHA:0:8} "
        git push
   
